language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script :
  - composer install

script: phpunit

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true